import { MODEL_ID } from "./model";
import type { ExamPattern } from "@/types/physics-model";

export const examPatterns: ExamPattern[] = [
  {
    id: "exam-heat-is-not-temperature",
    format: "multiple-choice",
    representation: "文字判断：温度是不是就是吸收的能量",
    testedModel: MODEL_ID,
    difficulty: "basic",
    requiredCognitiveActions: ["C3", "C4", "C9", "C13"],
    stem: "下面哪一句更合适？",
    representationOptions: [
      "温度和吸收的能量是不是同一件事",
      "杯子是什么颜色",
      "是不是课堂上的沙子",
      "题目有没有图",
    ],
    modelOptions: [
      "温度不是吸收的能量；还要看质量、比热容和温度变化",
      "谁更烫，吸收的能量一定更多",
      "比热容就是温度",
    ],
    options: [
      "温度不是吸收的能量。要比较谁吸热更多，还要看质量、比热容和升了几度。",
      "谁最后更烫，谁吸收的能量一定更多。",
      "比热容就是物体现在有多热。",
      "加热时间相同，吸收的能量和升温都一定相同。",
    ],
    correctAnswer:
      "温度不是吸收的能量。要比较谁吸热更多，还要看质量、比热容和升了几度。",
    commonDistractors: [
      "谁最后更烫，谁吸收的能量一定更多。",
      "加热时间相同，吸收的能量和升温都一定相同。",
    ],
    requiredReasoning: ["区分温度与能量", "指出还要看质量和比热容"],
    reasoningPrompt: "用你想到的关系写一句理由。不要只重复选项。",
  },
  {
    id: "exam-same-mass-same-delta-t-larger-c",
    format: "multiple-choice",
    representation: "文字情境：质量和升温相同，比热容不同",
    testedModel: MODEL_ID,
    difficulty: "basic",
    requiredCognitiveActions: ["C3", "C7", "C8", "C12"],
    stem: "两种材料质量相同，都要使温度升高 10℃。材料 A 的比热容是材料 B 的两倍。谁需要的能量更多？",
    representationOptions: [
      "质量和升温相同时谁需要的能量更多",
      "材料叫什么名字",
      "颜色深浅",
      "要不要先判断它能不能浮",
    ],
    modelOptions: [
      "同样质量升高同样温度，c 更大则 Q 更大",
      "升温相同则能量一定相同",
      "只要质量相同，能量就相同",
    ],
    options: [
      "A 需要的能量更多，因为同样质量升高同样温度时，比热容更大的需要更多能量。",
      "一样多，因为都升高了 10℃。",
      "B 需要的能量更多，因为比热容小的更难加热。",
      "无法比较，因为没有说出它们是不是固体。",
    ],
    correctAnswer:
      "A 需要的能量更多，因为同样质量升高同样温度时，比热容更大的需要更多能量。",
    commonDistractors: [
      "一样多，因为都升高了 10℃。",
      "B 需要的能量更多，因为比热容小的更难加热。",
    ],
    requiredReasoning: ["质量相同", "ΔT 相同", "Q 随 c 增大"],
    reasoningPrompt: "先写出哪个量相同，再说明能量怎样比。",
  },
  {
    id: "exam-same-mass-same-q-larger-c",
    format: "multiple-choice",
    representation: "文字情境：质量和吸收能量相同，比热容不同",
    testedModel: MODEL_ID,
    difficulty: "medium",
    requiredCognitiveActions: ["C7", "C8", "C10", "C11"],
    stem: "两份样品质量相同，吸收的能量也可以看成相同。甲的比热容更大。下面哪一句更合适？",
    representationOptions: [
      "质量和能量相同时温度怎样比",
      "样品值不值钱",
      "加热器是什么牌子",
      "是不是课堂上见过的沙子",
    ],
    modelOptions: [
      "同样质量吸收同样能量，c 更大则 ΔT 更小",
      "比热容大的一定升得更高",
      "能量相同则温度一定相同",
    ],
    options: [
      "甲的温度升得更少，因为同样能量分摊到更大的比热容上。",
      "甲一定更烫，因为比热容更大。",
      "两份温度变化一定相同，因为吸收的能量相同。",
      "只能说甲更重，不能谈温度。",
    ],
    correctAnswer: "甲的温度升得更少，因为同样能量分摊到更大的比热容上。",
    commonDistractors: [
      "甲一定更烫，因为比热容更大。",
      "两份温度变化一定相同，因为吸收的能量相同。",
    ],
    requiredReasoning: ["质量相同", "Q 相同", "ΔT 随 c 减小"],
    reasoningPrompt: "先写出哪个量相同，再说明温度变化怎样比。",
  },
  {
    id: "exam-calculate-q-from-c-m-delta-t",
    format: "calculation",
    representation: "计算：用 c、m、ΔT 求 Q",
    testedModel: MODEL_ID,
    difficulty: "medium",
    requiredCognitiveActions: ["C3", "C10", "C12"],
    stem: "2 kg 的水，比热容取 4.2×10³ J/(kg·℃)，温度从 20℃ 升到 30℃。它吸收的能量最接近哪一个？",
    representationOptions: [
      "用 c、m、ΔT 求 Q",
      "水是不是课堂上见过的",
      "20 大不大",
      "要不要先判断它会不会沸腾",
    ],
    modelOptions: [
      "Q = c m ΔT",
      "Q 等于温度的末值",
      "Q 等于加热的分钟数",
    ],
    options: [
      "8.4×10⁴ J",
      "4.2×10³ J",
      "30 J",
      "2×30 J",
    ],
    correctAnswer: "8.4×10⁴ J",
    commonDistractors: ["4.2×10³ J", "30 J"],
    requiredReasoning: ["认出 ΔT = 10℃", "代入 Q = c m ΔT"],
    reasoningPrompt: "写出你用到的量和计算。不要只抄得数。",
  },
  {
    id: "exam-heating-without-temperature-rise",
    format: "multiple-choice",
    representation: "条件判断：加热时温度可以不变",
    testedModel: MODEL_ID,
    difficulty: "medium",
    requiredCognitiveActions: ["C4", "C7", "C13"],
    stem: "一杯冰水混合物还在熔化。继续加热，温度计停在 0℃。下面哪一句更合适？",
    representationOptions: [
      "没有升温时还能不能直接用 Q = c m ΔT",
      "冰值不值钱",
      "加热器快不快",
      "杯子是不是透明的",
    ],
    modelOptions: [
      "没有 ΔT 时不能用这个式子写完熔化过程",
      "加热就一定升温",
      "温度不变说明没有吸收能量",
    ],
    options: [
      "这段过程有物态变化，不能只用 Q = c m ΔT 说明全部能量去向。",
      "温度没变，所以一定没有吸收能量。",
      "只要在加热，温度就一定会升高，一定是温度计坏了。",
      "比热容变成了零，所以公式仍然适用。",
    ],
    correctAnswer: "这段过程有物态变化，不能只用 Q = c m ΔT 说明全部能量去向。",
    commonDistractors: [
      "温度没变，所以一定没有吸收能量。",
      "只要在加热，温度就一定会升高，一定是温度计坏了。",
    ],
    requiredReasoning: ["检查有没有物态变化", "C13：没有 ΔT 则公式不够"],
    reasoningPrompt: "先判断条件够不够，再决定能不能直接用这个式子。",
  },
];
