import { MODEL_ID } from "./model";
import type { ExamPattern } from "@/types/physics-model";

export const examPatterns: ExamPattern[] = [
  {
    id: "exam-density-is-not-mass-or-size",
    format: "multiple-choice",
    representation: "文字判断：密度是不是就是轻重或大小",
    testedModel: MODEL_ID,
    difficulty: "basic",
    requiredCognitiveActions: ["C3", "C4", "C9", "C13"],
    stem: "下面哪一句更合适？",
    representationOptions: [
      "密度、质量和体积是不是同一件事",
      "样品颜色",
      "是不是课堂上的木块",
      "题目有没有图",
    ],
    modelOptions: [
      "密度是单位体积的质量，不等于“更重”或“更大”",
      "更重的物体密度一定更大",
      "看起来更大的物体密度一定更大",
    ],
    options: [
      "密度是单位体积的质量，不能只看谁更重或谁看起来更大。",
      "哪个更重，密度就一定更大。",
      "哪个看起来更大，密度就一定更大。",
      "密度就是质量的另一个名字。",
    ],
    correctAnswer: "密度是单位体积的质量，不能只看谁更重或谁看起来更大。",
    commonDistractors: [
      "哪个更重，密度就一定更大。",
      "哪个看起来更大，密度就一定更大。",
    ],
    requiredReasoning: ["区分密度与质量", "区分密度与体积/大小"],
    reasoningPrompt: "用你想到的关系，写一句理由。不要只重复选项。",
  },
  {
    id: "exam-same-volume-larger-mass",
    format: "multiple-choice",
    representation: "文字情境：体积相同比质量",
    testedModel: MODEL_ID,
    difficulty: "basic",
    requiredCognitiveActions: ["C7", "C8", "C10", "C11"],
    stem: "两块固体体积相同。甲的质量更大。下面哪一句更合适？",
    representationOptions: [
      "体积相同时质量和密度怎样比",
      "固体叫什么名字",
      "颜色深浅",
      "是不是金属",
    ],
    modelOptions: [
      "体积相同，质量更大则密度更大",
      "质量更大只说明它更重，和密度无关",
      "体积相同则密度一定相同",
    ],
    options: [
      "甲的密度更大，因为同样体积里质量更大。",
      "只能说甲更重，不能谈密度。",
      "体积相同，所以密度一定相同。",
      "甲看起来一样大，所以密度更小。",
    ],
    correctAnswer: "甲的密度更大，因为同样体积里质量更大。",
    commonDistractors: [
      "只能说甲更重，不能谈密度。",
      "体积相同，所以密度一定相同。",
    ],
    requiredReasoning: ["体积相同这一条件", "密度随质量增大"],
    reasoningPrompt: "先写出哪个量相同，再说明密度怎样比。",
  },
  {
    id: "exam-cut-uniform-density-unchanged",
    format: "multiple-choice",
    representation: "条件判断：均匀切开",
    testedModel: MODEL_ID,
    difficulty: "medium",
    requiredCognitiveActions: ["C4", "C7", "C10", "C13"],
    stem: "一块内部均匀的金属切成大小相等的两半。其中一半的密度会怎样？",
    representationOptions: [
      "均匀切开后密度是否改变",
      "刀是不是很快",
      "金属值不值钱",
      "切开后还叫不叫原来的名字",
    ],
    modelOptions: [
      "质量和体积按同样比例变，密度不变",
      "变小了所以密度变小",
      "变轻了所以密度变小",
    ],
    options: [
      "这一半的密度和原来几乎一样，因为质量和体积都大约变成一半。",
      "体积变小了，密度一定变小。",
      "质量变小了，密度一定变小。",
      "切开会让材料变成另一种物质，密度无法比较。",
    ],
    correctAnswer:
      "这一半的密度和原来几乎一样，因为质量和体积都大约变成一半。",
    commonDistractors: [
      "体积变小了，密度一定变小。",
      "质量变小了，密度一定变小。",
    ],
    requiredReasoning: ["均匀样品条件", "ρ = m / V 在比例变化下不变"],
    reasoningPrompt: "切开后，哪个量变了，哪个量的关系没变？",
  },
  {
    id: "exam-calculate-density-ratio",
    format: "calculation",
    representation: "计算：用质量和体积求密度",
    testedModel: MODEL_ID,
    difficulty: "medium",
    requiredCognitiveActions: ["C3", "C10", "C12"],
    stem: "一个均匀小块质量是 27 g，体积是 10 cm³。它的密度最接近哪一个？",
    representationOptions: [
      "用 m 和 V 求 ρ",
      "物体是不是课堂上见过的",
      "27 大不大",
      "要不要先判断它能不能浮",
    ],
    modelOptions: [
      "ρ = m / V",
      "密度等于质量",
      "密度等于体积",
    ],
    options: [
      "2.7 g/cm³",
      "27 g/cm³",
      "10 g/cm³",
      "0.37 g/cm³",
    ],
    correctAnswer: "2.7 g/cm³",
    commonDistractors: ["27 g/cm³", "10 g/cm³", "0.37 g/cm³"],
    requiredReasoning: ["写出 ρ = m / V", "代入 27 / 10"],
    reasoningPrompt: "写出你用的关系，再说明数字是怎么来的。",
  },
  {
    id: "exam-mass-volume-density-table",
    format: "diagram",
    representation: "表格：质量、体积与密度",
    testedModel: MODEL_ID,
    difficulty: "medium",
    requiredCognitiveActions: ["C3", "C8", "C9", "C12"],
    stem: "表中两行体积都是 10 cm³。甲质量 79 g，乙质量 6 g。根据表，下面哪一句最合适？",
    representationOptions: [
      "表上质量和体积怎样对应到密度",
      "甲乙叫什么材料",
      "表格线粗不粗",
      "有没有画样品外形",
    ],
    modelOptions: [
      "同样体积下，质量更大则密度更大",
      "谁质量大谁体积就一定大",
      "表上看起来有两行，所以密度相同",
    ],
    options: [
      "甲的密度更大，因为同样 10 cm³ 里质量更大。",
      "乙体积也是 10 cm³，所以两人密度一定相同。",
      "甲更重，所以甲的体积一定更大，表一定抄错了。",
      "没有浮沉信息，所以这张表不能谈密度。",
    ],
    correctAnswer: "甲的密度更大，因为同样 10 cm³ 里质量更大。",
    requiredReasoning: ["读表时同时用到质量和体积", "不把密度说成浮沉"],
    reasoningPrompt: "结合表里的两个量，说明你怎样比较密度。",
  },
];
