export {
  createInitialConvexLensState,
  convexLensPhysicsSnapshot,
  isConvexLensSceneState,
  isLensExperimentId,
  isObjectStation,
  officialBenchDisplay,
  prepareLensExperimentState,
  runConvexLensExperiment,
  runObserveDemo,
  screenDoesNotMoveImage,
  LENS_EXPERIMENT_A,
  LENS_EXPERIMENT_B,
  LENS_EXPERIMENT_C,
  LENS_EXPERIMENT_D,
  LENS_EXPERIMENT_ORDER,
  LENS_OBSERVE_DEMO_STATIONS,
  type ConvexLensExperimentResult,
  type ConvexLensSceneState,
  type LensExperimentId,
  type OfficialBenchDisplay,
} from "./types";
