export {
  SAMPLE_CATALOG,
  SAMPLE_IDS,
  SAMPLES_EXPERIMENT_A,
  SAMPLES_EXPERIMENT_B,
  SAMPLES_EXPERIMENT_C,
  SAMPLES_EXPERIMENT_ORDER,
  applyCutFactor,
  createInitialDensityState,
  densityGPerCm3,
  expectedDensityFor,
  isDensitySceneState,
  isSampleId,
  isSampleState,
  prepareExperimentState,
  runObserveDemo,
  runSamplesExperiment,
  samplesPhysicsSnapshot,
  visibleSamples,
} from "./types";
export type {
  ComparisonMode,
  DensitySceneState,
  SampleId,
  SampleState,
  SamplesExperimentId,
  SamplesExperimentResult,
} from "./types";
